project:
  type: website

website:
  google-analytics: "G-7B3QTM28NP"
  title: ":)"
  navbar:
    logo: "flower.png"
    left:
      - href: index.qmd
        text: Home sweet home
      - href: everything.qmd
        text: everything
      - href: everywhere.qmd
        text: everywhere
      - href: all_at_once.qmd
        text: all at once
        
  page-footer: 
    right: "&copy; 2024, Mel"
format:
  html:
    theme: Litera
    css: styles.css
    toc: true
