project:
  type: website

website:
  title: ":)"
  navbar:
    left:
      - href: home.qmd
        text: Home sweet home
      - href: everything.qmd
        text: everything
      - href: everywhere.qmd
        text: everywhere
      - href: all_at_once.qmd
        text: all at once
      - href: curious.qmd
        text: curious?
        
  page-footer: 
    right: "&copy; 2024, Mel"
format:
  html:
    theme: Litera
    css: styles.css
    toc: true

execute: 
  freeze: auto