project:
  type: website

website:
  title: "Michelle's Website"
  navbar:
    left:
      - href: index.qmd
        text: Home page
      - href: projects.qmd
        text: Projects
      - href: about.qmd
        text: Everything Else
        
  page-footer: 
    right: "&copy; 2024, Mingchen Wang"
format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

execute: 
  freeze: auto