project:
  type: website

website:
  title: "Michelle's Website"
  navbar:
    left:
      - href: index.qmd
        text: Home page
      - href: about.qmd
        text: About me

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



