---
title: "Everything, everywhere, all at once."
---

I enjoy trivia, random facts, puzzles, odd questions, and bad jokes. 
Here's some of them.

*  Owls don’t have eyeballs, (they have eye tubes or cylinders, rod* shaped eyes that do not move in their sockets as eyeballs do) 
*  Snow is red on Pluto 
*  Sunset is blue on mars 
*  McDonald once had cilantro flavored ice cream 
*  McDonald once also had bubble gum flavored broccoli 
*  Jamaica has 120 rivers 
*  30.1% of Starting number is 1 in markets, 4.6% is 9 (Benford's law) 
*  There are only 4 languages in the world where it goes Object Subject Verb (Apples love I) 
*  If you can make a bathtub bigger than Saturn, Saturn will float like a rubber duck 
*  Algonquin people are a tribe of indigenous people who now living in eastern Canada. They speak The Algonquin language, which is a part of the Algonquian language family. Algonquins are known for their works with beads. Many of their clothes are decorated with colorful beads. They were very famous for the stories they told. 
*  The five Algonquian tribes are a group of native American tribes. They traditionally spoke similar languages, and has similar ways of life. They contain the Cree, the Mohican, the Delaware, the Ojibwa, the Shawnee and the Algonquin.
*  When an NFT is created (artist mints NFT), it is added in block chain through energy intensive computer mining, this has the same carbon footprint as driving a car for 500 miles
*  Purple is the most expensive colors in the early days, it is extracted from snail shells 
*  Two words that are pronounced almost the same worldwide: coffee and chocolate 
*  Vanilla flavoring came from anal excretions of beavers 
*  Suriname toad, Pipa pipa, at the Saint Louis Zoo. Females of this species birth their young from holes in their backs.
*  Once a shark spited out a human arm in a museum, and that's how a perfect murder case is sloved. 
